
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: like_dislike_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: like_dislike_test
  username: postgres
  password: postgres


production:
  <<: *default
  database: like_dislike_production
  username: postgres
  password: postgres
